apiVersion: apps/v1
kind: Deployment
metadata:
  name: rento-app
  namespace: rento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rento-app
  template:
    metadata:
      labels:
        app: rento-app
    spec:
      containers:
        - name: rento-app
          image: ajayab05/rento-app:latest   # replace with your image tag
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: "rento.czwg6q626yxo.ap-south-1.rds.amazonaws.com"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "admin123"
            - name: DATABASE_NAME
              value: "rento"
            - name: DATABASE_SSL_ENABLED
              value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: rento-service
  namespace: rento
spec:
  type: NodePort
  selector:
    app: rento-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 30080   # external port for access

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rento-ingress
  namespace: rento
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rento-service
                port:
                  number: 80
