services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: rento
      POSTGRES_USER: rento_user
      POSTGRES_PASSWORD: rento_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rento_user -d rento"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://rento_user:rento_password@db:5432/rento
    ports:
      - "3000:3000"

